### ISSUE TITLE
Translation not supported

### ISSUE THREAD

**Issue by fn-obvsg** [CARLI/letters-addressfrom-editor#1]
This cloud app is a great thing - many thanks for it.
But unfortunately, we can't edit the label in the Translation column.
Non-English speaking countries use the translations in the labels. Can you add this?
Thank you and best regards Fritz

**Comment by cedelis** [comment]
Hello, Fritz,

Thank you for sending us your feedback. I'm glad to find the cloud app was useful for you!

Since this cloud app was designed with a very specific purpose in mind -- to quickly and easily set the email address values of the 'addressFrom' label -- I don't quite understand why you would want to translate an email address value. Perhaps, I'm not understanding your proposed feature request. Are you suggesting that the interface itself allow for translation of the labels used in the user interface, e.g., the buttons (Retrieve Letters, Clear, Sort by addressFrom, Sort by Letter, Update)?

Thanks,
Chris

**Comment by fn-obvsg** [comment]
Dear Chris,

thank you for your reply and query.
I probably didn't express myself clearly - I'm sorry.
We always work "bilingually" with the letters / letter labels.
This means that we use the English-language labels and the German-language labels in the translation.
The entry in the "addressFrom" label clearly has the same content for both languages.
We would also like to be able to change the entry in the German-language labels with your cloud app.
Please let me know if I have expressed myself unclearly again / if something is still unclear.
Thanks again for your email and best regards from Vienna,
Fritz

![example of the labels of the_Borrowing Activity Letter](https://github.com/CARLI/letters-addressfrom-editor/assets/172611059/a3b9046f-057a-4ed6-8c37-595352af705d)

**Comment by kratzerm** [comment]
Dear Chris,

On behalf of both the Bavarian State Library and the regional State Libraries of Bavaria thank you so much for sharing this great app! 

>  I don't quite understand why you would want to translate an email address value.

I couldn't agree more. Problem is: Ex Libris has implemented the addressFrom as a label and - like for each of the other labels - even provides a default translation (in German: "Ihre.Abteilung@organisation.com") for the default addressFrom value "Your.Department@organization.com" X-(

So I'd like to second Fritz' issue report because your app currently only allows us to replace the English default values for addressFrom in all letters but not the German translation provided by Ex Libris. If Ex Libris had just left this translation empty I'm quite sure we would be fine because if there is no German translation available Alma should just take the (untranslated) value from the field "Description". On the other hand: The fact that the English "translation" seems to be just a non-editable copy of the value in "Description" could indicate that Alma requires a translation and that an empty translation field could well result in a blank from adress. OMG - you can never be sure that Ex Libris has implemented it like any of us would have implemented it ...  

In any case it would problaby be the solution for 99.9 % of Alma customers if your app just wrote the adress specified in the user interface to both "Description" and to any translation field contained in the JSON object. However, some day you might be contacted by one of those 0.1 % other Alma customers who really want their English e-mails to be sent from an "English" address and e-mails in other languages to be sent from specific other addresses. I18n is not a trivial problem ;-)

Best regards
Mathias

**Comment by cedelis** [comment]
@kratzerm  and @fn-obvsg ,

Thank you both for providing me with clarification. I think I now understand the problem :) 

I will keep you posted.

Thank you,
Chris

**Comment by cedelis** [comment]
@kratzerm 
@fn-obvsg ,

I have added support for multiple languages. After testing this new feature a bit more, I plan to publish a release.

The cloud app will now check Alma configuration for all enabled languages (via the Alma API: /conf/mapping-tables/InstitutionLanguages which is the same information found in the User Interface: Configuration > General > Institutional Languages). If there are more than one enabled languages, then you will be able to choose which language to edit.

Here's a screenshot to give you an idea:

<img width="449" alt="Screenshot 2024-07-17 at 3 53 39 PM" src="https://github.com/user-attachments/assets/cd282095-7cf2-48ed-9835-9ee4d110305f">

It might be difficult to see in the first screenshot, but to the right of "Language:" there is a pull-down menu. Clicking on that menu, you can see the available languages you may edit:

<img width="449" alt="Screenshot 2024-07-17 at 7 58 17 PM" src="https://github.com/user-attachments/assets/62d117f9-4900-4837-a07f-500669f7d3cc">

**Comment by cedelis** [comment]
Thought I'd share a "progress" report:

The reason this is taking longer than I had expected is because I'm experience some very strange results using the Alma API. I'm attempting to add the new Translations feature as stable as possible given these circumstances.

Here are some of the notes and observations that I've put together thus far while working on this new feature:

Alma Letters addressFrom labels and translations
================================================

(*) addressFrom labels need to be edited en mass easily so that we can conform to our DMARC policy

(*) The Letters Configuration interface in Alma is laborious as you can only edit one letter at a time (and also one translation at a time)

(*) The list of Letters is gathered (GET) via the /conf/letters API method

(*) labels for a particular Letter can be gathered (GET) and updated (PUT) via the /conf/code-tables/xxx API method, e.g., /conf/code-tables/ResetPwLetter

(*) labels for a particular language can be gathered (GET) and updated (PUT) via the lang parameter, e.g., /conf/code-tables/ResetPwLetter?lang=de

How translations "work":

(*) label Descriptions are stored in the English (en) language code-table, e.g., /conf/code-tables/ResetPwLetter?lang=en

(*) label Translations are stored in the language-specific code-table, e.g., German (de), /conf/code-tables/ResetPwLetter?lang=de

Odd behavior (bug?) discovered:

* Sometimes, if you update a Translation via the Letters Configuration editor (or even via the API), you also need to update the Description via API (even if the Description hasn't changed)

E.g., 

---------------------------
update German translation via Letters Configuration editor
the German translation shows up in API call as expected

update German translation via API
the German translation up in API call as expected (unfortunately, sometimes it does *not* show up)
but the German translation does not show up in Letters Configuration editor (unfortunately, sometimes it *does* show up)

work-around that seems to always work:
update German translation via Letters Configuration editor (or via API)
update the English description via API
the German translation now shows up in Letters Configuration editor
---------------------------

Another seriously odd behavior (bug?) discovered:

* It seems that the most recent API call using the 'lang' parameter adversely affects the Alma session. E.g., if your Alma session is in German and the most recent (final) API call used 'lang=es', then when you leave the Cloud App and return to Alma, you will notice that web pages will begin to be translated to this most recent language, e.g., Spanish (however, I notice that the action buttons aren't affected). I believe I've found a work-around for this which is to make sure that the Cloud App always makes an API call using a blank value for 'lang', e.g., /conf/code-tables/ResetPwLetter?lang= ; this seems to 'reset' Alma back to its original language (e.g., German)

**Comment by cedelis** [comment]
I've released version 1.1-beta today ( https://github.com/CARLI/letters-addressfrom-editor/releases/tag/v1.1-beta ). You may now try this new version in Alma. Thank you, all, for bringing this to my attention! Cheers, Chris

**Comment by kratzerm** [comment]
Thank you for adding translation support so quickly - works like a charm!

Best wishes
Mathias

**Comment by fn-obvsg** [comment]
Dear Chris,

many thanks from me too - it works perfectly.
Best regards, Fritz
